### ISSUE TITLE
Communication to Hardware via jackal_control [Question]

### ISSUE THREAD

**Issue by Doctor-N0** [jackal/jackal#126]
I was wondering how the control commands, which are calculated using [jackal_control](https://github.com/jackal/jackal/tree/noetic-devel/jackal_control), are actually transmitted to the electrical drive system. In [ros_control ](https://slaterobotics.medium.com/how-to-implement-ros-control-on-a-custom-robot-748b52751f2e) it is suggested to do this via the read() and write() functions in the hardware_interface.cpp file. However, I have not found any corresponding files in this repository. Therefore, I assume that the connection is done via CAN bus, OPC-UA or a similar protocol?

Thank you in advance for your answer!

**Comment by tonybaltovski** [comment]
It uses `rosserial` to talk to the Jackal's mircocontroller starting here: https://github.com/jackal/jackal_robot/blob/noetic-devel/jackal_base/src/jackal_base.cpp#L88 and the hardware_interface in jackal_interface.

**Comment by Doctor-N0** [comment]
Thanks!
