### ISSUE TITLE
Gazebo Laser Plugin

### ISSUE THREAD

**Issue by Cavalletta98** [jackal/jackal#129]
Hi, i'm running the simulation on Ubuntu 20.04 with ROS Foxy. I noticed that it is not possible to simulate a Laserscan because it is not present as gazebo plugin with name `libgazebo_ros_laser.so`. In ROS2, should be `libgazebo_ros_ray_sensor.so`.
Can you please help me to simulate it?
Thanks

**Comment by tonybaltovski** [comment]
@Cavalletta98 can you try `foxy-devel` from source as #130 should fix your issue.

**Comment by Cavalletta98** [comment]
Is It updated also the apt package?

**Comment by tonybaltovski** [comment]
I have a made a new release of `1.0.3` with the fix.  It will be on Open Robotics' package server at the next sync and on [Clearpath's package](http://wiki.ros.org/ClearpathRobotics/Packages) server soon.
