### ISSUE TITLE
Guide for navigation ROS Foxy

### ISSUE THREAD

**Issue by Cavalletta98** [jackal/jackal#131]
Hi, is ti possible to have a guide with some steps for navigating with the jackal either in simulation and reality?
Thank you

**Comment by tonybaltovski** [comment]
This is something we are working on.

**Comment by Cavalletta98** [comment]
When Will be available?

**Comment by jb-balaji** [comment]
Since Foxy is EOL, will there be support for Humble version? Any documentation or pointer will be of help. thanks.

**Comment by tonybaltovski** [comment]
There are here now: https://docs.clearpathrobotics.com/docs/ros/tutorials/navigation_demos/overview
