### ISSUE TITLE
Problem visualizing in Rviz

### ISSUE THREAD

**Issue by Cavalletta98** [jackal/jackal#134]
Hi, i'm running ubuntu 20.04 with ROS Foxy and i'm not able to use Rviz for SLAM navigation.
I'm running the following commands on different terminals:

- `ros2 launch jackal_gazebo jackal_world.launch.py`
- `ros2 launch jackal_navigation nav2.launch.py slam:=true use_sim_time:=true`
- `ros2 launch jackal_viz view_robot.launch.py `
For the command  `ros2 launch jackal_navigation nav2.launch.py slam:=true use_sim_time:=true`, i'm getting this error `[controller_server-2] [INFO] [1676476626.544682832] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'front_laser' at time 1581.062 for reason 'Unknown'`.
For the command `ros2 launch jackal_viz view_robot.launch.py `, i'm getting this warning `[rviz2-1] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-1]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.13/src/buffer_core.cpp` and i'm not able to see the robot like in the picture atached
![rviz](https://user-images.githubusercontent.com/45316566/219082153-267f282d-dc6c-42b6-a71f-8e26589c1418.png)
![rviz1](https://user-images.githubusercontent.com/45316566/219082512-d8615073-249d-4009-9799-e41e933b08d9.png)
Can you help me?

**Comment by tonybaltovski** [comment]
This issue of not seeing the information in rviz is due to your fixed frame being map which is not being published.  Switch it to base_link and it will work.

**Comment by Cavalletta98** [comment]
It Is not normal that the map Is not published. Since i have to send a goal to the jackal,i should be in the map frame as fixed frame

**Comment by tonybaltovski** [comment]
Yes but rviz is behaving as expected when the frame is missing. #132 is the root cause.
