### ISSUE TITLE
Issue with TF Transformation in ROS: No Transform from base link to odom

### ISSUE THREAD

**Issue by MohamedHabbad** [jackal/jackal#143]
Hello everyone,

I am currently facing an issue with TF transformation in ROS, specifically regarding the transformation from the base link to odom frame. I would like to provide a detailed description of the problem thats why i made that in steps-form with some pictures for details , those are the steps that i have taken so far in order to seek assistance and possible solutions :

1.
   - I have a computer and a Jackal robot connected to the same subnet.
   - On my computer i opened a terminal and set the ROS_MASTER_URI to http://192.168.1.130:11311/ to access the Jackal's ROS master.
2.
   - Using the Jackal's terminal i can successfully access the topics by running the command `rostopic echo /tf` to receive data from the Jackal.
![rostopic echo tf](https://github.com/jackal/jackal/assets/136476747/b2877fb6-6b24-4801-8735-2d13fd4beaab)
3.
   - To visualize the data on my own computer i opened a new terminal and established access to the Jackal's master by setting the ROS_MASTER_URI as mentioned before.
   - Upon launching RViz in my terminal i become an error message saying "No Transform from base link to odom" and related issues.

4.Troubleshooting Steps:
   - I checked the topics by running `rostopic list` in both terminals, and they displayed the same topics.
![rostopiclist](https://github.com/jackal/jackal/assets/136476747/dc00354d-4a63-4977-b69c-9e5764922be7)
   - I verified that the network connection between my computer and the Jackal was stable and functional.
   - I ran `rostopic echo /tf` in the Jackal's terminal and confirmed that TF data was being transmitted successfully ,however, when i ran the same command in my terminal, the system became unresponsive.
   
![Prssssob](https://github.com/jackal/jackal/assets/136476747/82608e93-2bbd-402c-84b4-693e81b614a9)

5. Attempted Solution:
   - While researching the issue online, I came across a suggestion to modify the launch file by adding the following lines:
     ```xml
     <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" />
     <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />
     ```
   - After implementing these changes i launched the `odom_navigation` launch file in the Jackal's terminal and started RViz in my terminal.
   - This modification allowed RViz to partially function, but i got a new problem. Initially, RViz displayed "odom" as the Fixed Frame, but once i changed it, only the links defined in the URDF file were shown. The "odom" frame was no longer available.
   
![Problem1](https://github.com/jackal/jackal/assets/136476747/29ee8562-3959-40d0-8d70-0af88eb3e275)
![Problem2](https://github.com/jackal/jackal/assets/136476747/6c417972-2b2e-4a24-a8eb-f712b6b9884a)
![Problem3](https://github.com/jackal/jackal/assets/136476747/66fabb5f-6ae2-49a1-9982-f69e01248db3)

Considering those information i would really appreciate any suggestions or solutions regarding the following aspects:

1. The initial issue of "No Transform from Base Link to odom" and the No-response of the system when running `rostopic echo /tf` in my terminal.
2. The modification to the launch file that enabled RViz to partially function but resulted in the "odom" frame disappearing from the Fixed Frame options.

Thank you a lot for your time and your support

**Comment by civerachb-cpr** [comment]
Have you set the `ROS_IP` and/or `ROS_HOSTNAME` environment variables on your laptop?

Normally we recommend using hostnames instead of IP addresses, and modifying `/etc/hosts` on both the robot and your laptop so that each can resolve the hostname of the other:

## On the robot

`/etc/hosts`
```
# replace this IP address with your laptop's address on the wireless network
# if you use DHCP you may need to update it regularly as your DHCP allocation
# rotates
192.168.1.129      thga
```

## On your laptop

`/etc/hosts`
```
192.168.1.130      cpr-j100-0330
```

Then to you connect to the Jackal's ROS master:

```bash
export ROS_MASTER_URI=http://cpr-j100-0330:11311

rostopic list

rostopic echo /tf
```

See http://www.clearpathrobotics.com/assets/guides/noetic/jackal/network.html#remote-ros-connection for more information.

**Comment by MohamedHabbad** [comment]
Thank you so much ! it works :+1:
