### ISSUE TITLE
How can I upgrade the jackal firmware in the ros-foxy version?

### ISSUE THREAD

**Issue by ans2568** [jackal/jackal#145]
I attempting to upgrade from ROS 1 to ROS 2 using the following two links.

https://clearpathrobotics.com/assets/guides/foxy/jackal/ROSUpgrade.html

https://clearpathrobotics.com/assets/guides/foxy/jackal/JackalInstallRobotSoftware.html

While executing the command ```sudo apt-get install ros-foxy-jackal-firmware```,  I encountered an error
```E: unable to find ros-foxy-jackal-firmware```

How can I resolve this issue?

I already install micro-ROS, ROS-foxy, ubuntu-20.04 version.

I would appreciate your response.
Thanks.

**Comment by civerachb-cpr** [comment]
The Jackal firmware package is available through Clearpath Robotics' `apt` package server. You can follow the instructions at http://packages.clearpathrobotics.com to add these servers to your apt sources.

If you need a direct link to the package, it is located here: https://packages.clearpathrobotics.com/stable/ubuntu/pool/main/j/jackal-firmware/

**Comment by ans2568** [comment]
I appreciate your response. I have successfully installed the ROS Foxy Jackal firmware.
