### ISSUE TITLE
Rviz Error: No Map Received

### ISSUE THREAD

**Issue by amiyajima** [jackal/jackal#42]
We ran `roslaunch jackal_navigation gmapping_demo.launch` but in rviz we see the point cloud but no map is produced. Under the map tab we see an error saying "No Map Received". 

Is this an issue with gmapping configurations?

**Comment by tonybaltovski** [comment]
The gmapping demo is configured for a 2D laser scanner.  I assume you are not using one since you are seeing point clouds?  You can use [pointcloud_to_laserscan](http://wiki.ros.org/pointcloud_to_laserscan) to convert from3D Point Cloud into a 2D laser scan for gmapping.

**Comment by MengGuo** [comment]
We have Velodyne on board, which is a laser scanner, right? the visualization in Rivz is subscribed to point cloud though. How should we configure `gmapping` with `Velodyne` then?

**Comment by tonybaltovski** [comment]
Create a launch file to use `pointcloud_to_laserscan` such as the one below and add it to the upstart job.  Make sure `pointcloud_to_laserscan` is installed.

```
<node pkg="pointcloud_to_laserscan" type="pointcloud_to_laserscan_node" name="pointcloud_to_laserscan">

    <remap from="cloud_in" to="/velodyne_points"/>
    <remap from="scan" to="/front/scan"/>
    <rosparam>
        transform_tolerance: 0.01
        min_height: 0.25
        max_height: 0.75

        angle_min: -1.5708
        angle_max: 1.5708
        angle_increment: 0.087
        scan_time: 0.1
        range_min: 0.9
        range_max: 130
        use_inf: true
        concurrency_level: 0
    </rosparam>

</node>
```

**Comment by MengGuo** [comment]
Thanks! where is the upstart file normally located in Jackal?

**Comment by tonybaltovski** [comment]
No worries.  Make your launch file and a good idea would be to test it.  Once you verified it works, you can add it to upstart job using `rosrun robot_upstart install my_custom_package/launch --job ros --augment`.

**Comment by MengGuo** [comment]
Got it. Is that permanent or it needs to be done each time I turn Jackal on?

**Comment by tonybaltovski** [comment]
It will be permanent when the upstart job is augmented.

**Comment by MengGuo** [comment]
It worked, Tony. Thanks!

**Comment by tonybaltovski** [comment]
May I close this issue?

**Comment by MengGuo** [comment]
Yep, thanks!

**Comment by syqssyy** [comment]
i
