### ISSUE TITLE
Rviz error for amcl_demo

### ISSUE THREAD

**Issue by MengGuo** [jackal/jackal#43]
Hello Tony, 

we have reached the last part of the tutorial. We generate a .yaml map using gmapping and installed amcl on Jackal. 

When we launched the amcl_demo.launch, Jackal is not showing up in Rviz see the figure below:

![screenshot from 2016-10-11 17_04_55](https://cloud.githubusercontent.com/assets/8036243/19312091/fc66404e-905e-11e6-867a-f4c9c9e7e3d3.png)

any idea what might be the reason? Thanks,
/Meng

**Comment by tonybaltovski** [comment]
Looking at image you posted, getting data to the desktop machine.  Can you try echoing the tf topic using `rostopic echo /tf` on the desktop machine?

**Comment by MengGuo** [comment]
Hi Tony, the error disappeared after we restart the Jackal. We think it is a network issue. 

Also, for other people's reference, the `amcl_demo`also needs the`pointcloud_to_laserscan` since we have Velodyne.
