### ISSUE TITLE
Kinetic?

### ISSUE THREAD

**Issue by liborw** [jackal/jackal#46]
Has anyone tried to use jackal with kinetic?

**Comment by UltronDestroyer** [comment]
@liborw We are planning a July-August release.

**Comment by rarmstrong22** [comment]
Any word on the Kinetic release? I see there's a kinetic-devel branch.

**Comment by dniewinski** [comment]
Sorry for the delay on this.  Kinetic is currently in development and we are are hoping to release it within the next month or two.  This issue will be updated when that is completed.

**Comment by rgreid** [comment]
Hi guys, any update on the Kinetic release? Thanks.  @dniewinski @ibaranov-cp

**Comment by dniewinski** [comment]
Despite many delays, we have finally finished and released support for Kinetic! Many of the packages should be available through http://packages.ros.org or from http://packages.clearpathrobotics.com
