### ISSUE TITLE
VLP-16 in Simulation - 3D Pointcloud

### ISSUE THREAD

**Issue by mastash3ff** [jackal/jackal#58]
Any plans to support the VLP-16 or any 3D pointcloud capable device for the Jackal?  Would appreciate any pointers or guidance in the right direction for configuring the Jackal to support the VLP-16.

**Comment by civerachb-cpr** [comment]
Experimental support for the VLP-16 is in the azure_kinect branch.  We are not sure how much of this branch will be released to the main releases, but it should give you pointers on how to add the VLP-16 to your robot.

Without using the azure_kinect branch, the easiest solution would be to create a URDF file that adds the VLP16 macro to the robot:

`<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <xacro:macro name="vlp16_mount" params="prefix topic parent_link">
    <VLP-16 parent="${parent_link}" name="${prefix}_velodyne" topic="${topic}" hz="10" samples="1024" gpu="false" lasers="16" max_range="100">
      <origin xyz="$(optenv JACKAL_LASER_OFFSET 0 0 0)" rpy="$(optenv JACKAL_LASER_RPY 0 0 0)" />
    </VLP-16>
  </xacro:macro>`

and use the JACKAL_URDF_EXTRAS environment variable to add this URDF file to the robot's description.

Adding the VLP16 launch file to /etc/ros/*/ros.d with the appropriate parameters will launch the driver on startup.
