### ISSUE TITLE
Maximum speed of robot

### ISSUE THREAD

**Issue by aaky** [jackal/jackal#59]
Hello, 
  I tried to run simulation of robot with gazebo and amcl navigation demo with default map present in your repository with max velocity of 0.5 m/sec and it worked awesome. I wanted to understand even in simulation if I want to increase max velocity of robot to 2 m/sec or 3 m/sec so is it possible to do gazebo simulation with this velocity ? I tried with max velocity of 2 as well as 3 m/sec but robot drifts alot and also flips while travelling on the path.

**Comment by tonybaltovski** [comment]
Hello!

Great questions! Unfortunately this isn't quite the correct place for it, that's not something that we can inherently support. Your best bet would be to ask the ROS answers community, (https://answers.ros.org/questions/) there's usually plenty of ROS experts there that will be willing to help.

Best of luck!
